### ISSUE TITLE
Key MV_analysis/layer_1/signal_conv2d_1/bias not found in checkpoint

### ISSUE THREAD

**Issue by pragyak412** [RenYang-home/HLVC#2] opened 2020-12-07 06:18 UTC
Please Check this error!
```
Traceback (most recent call last):
  File "HLVC_layer2_P-frame.py", line 93, in <module>
    saver.restore(sess, save_path=model_path)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MV_analysis/layer_1/signal_conv2d_1/bias not found in checkpoint
         [[node save/RestoreV2 (defined at HLVC_layer2_P-frame.py:90) ]]
```

**Comment by RenYang-home** [comment] 2020-12-07 09:01
Which tensorflow and tensorflow-compression versions do you use? Thses codes, especially the pretrained models, only support tensorflow 1.12 and tensorflow-compression 1.0

**Comment by pragyak412** [comment] 2020-12-07 09:15
```
pragkuma@192 HLVC % pip install tensorflow==1.12
ERROR: Could not find a version that satisfies the requirement tensorflow==1.12 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4)
ERROR: No matching distribution found for tensorflow==1.12
```

I was using TensorFlow 1.14.0 and TensorFlow-compression 1.3.  I am now able to downgrade the TensorFlow to 1.12

**Comment by RenYang-home** [comment] 2020-12-07 09:22
If intending to use the pre-trained models, you have to downgrade to tf 1.12 and tfc 1.0. If you want to use higher versions, you could re-train the codes by yourself. I will currently close this comment, if the problem is not solved by downgrading or if there is any problem when re-training, please feel free to re-open the issue. Thanks.

**Closed as completed by RenYang-home** 2020-12-07 09:22 UTC
